### ISSUE TITLE
nouveau patient adulte - pb  function format() 

### ISSUE THREAD

**Issue by aaa34169** [LempereurMat/AQM#1]
j ai le message suivant apres avoir ajoute un nouveau patient adulte : 
les champs, ipp , nom, prenom, patho , dob ont ete renseignes et j ai juste valide hopital et commentaire. 

le mnessage est 
![2018-06-13 10_53_47-mozilla firefox](https://user-images.githubusercontent.com/3098117/41344246-836babb4-6ef8-11e8-9470-b0cbe8a94611.png)

merci d avance ?

**Comment by LempereurMat** [comment]
Modification du champ Date de Naissance en type Text
